os: linux
dist: focal
language: java
jdk: oraclejdk15
  
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      after_success:
        - cd ..
      before_deploy:
        - ./internal-package.sh config-osx
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: whork-desktop-$TRAVIS_TAG-osx.jar
        on:
          tags: true
    - os: linux
      dist: focal
      addons:
        sonarcloud:
          organization: "stefanobelli"
          token:
            secure: "IIg5LhjywAIhsNb1Zr9ZtCBam2DMLz2FdtFfEmMc/Dw5qDVtO9GlbsVw94LTEJZ3sDNMukSx9gXALLhKd3+acOKnVRY8vcxlPALkjtOnsvAwdUaKhvgS0vKuOtj7Knv00ZI96BMoXXyAauV/f+VwsXJNjaKM/o4Zz1q+ovmPzkDhWBKGHAFupvtVwSP5S3BJd2zQD0e2VrtAQkP9MUfbabZokxHDYxvQyxecPB/Ihr9xzIt2HBHy7IPN8dsVNYkn4zJtxaOxb9wGDnK9JjYJ9DbY+XxUTF7MxO6nbg40UKuoaJl9O8SOWS5wYuyqiz37wXTrFGmPsORs1HoMTswC9z00Y85n2Z2mskuwxje/5np4BaEDstKb9DzauVYK8TMATfgUJ3/xwsEyx755ZV91BUHGqCpI4phPwmVB+jhq0weu0TqHDuBPMKFgX6P+fzbd9r7S05S2kox+S8LiSAQqazFHFJxiY5xOwYhv+ZMu5hutEkw8yDdBAJ65N50uGwA6PROM9T+90LY1moHStMj1T2QbknTo9htX48uSJ9SaODDRhqQGi95m29Z+R8G8ghcDxpJZV78U/RsPQx4n521IA42d3ZEHh7VZJDaYGGJx7QAdtBCdku1smlCgYXmoJeaHJT0/GF7ZOBMXEvHH8HFhmNILIjGUXTucj+Ykkb/bK7A="
      after_success:
        - cd ..
        - sonar-scanner
      before_deploy:
        - ./internal-package.sh config-linux
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: 
          - whork-webapp-$TRAVIS_TAG-any.jar
          - whork-desktop-$TRAVIS_TAG-linux.jar
        on:
          tags: true
      

# BEGIN Common phases

before_script:
  - cd cool_project
  - mvn -version
script: 
  - mvn compile
  - mvn test

# END Common phases
