os: linux
dist: focal
language: java
jdk: oraclejdk15

jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      after_success:
        - cd ..
      before_deploy:
        - ./internal-package.sh config-osx
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: whork-desktop-$TRAVIS_TAG-osx.jar
        on:
          tags: true
    - os: linux
      dist: focal
      addons:
        sonarcloud:
          organization: "stefanobelli"
          token: $SONAR_TOKEN
      after_success:
        - cd ..
        - sonar-scanner
      before_deploy:
        - sudo apt install -y texlive texstudio
        - ./internal-package.sh config-linux
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: 
          - whork-webapp-$TRAVIS_TAG-any.jar
          - whork-desktop-$TRAVIS_TAG-linux.jar
          - whork-docs-$TRAVIS_TAG.zip
        on:
          tags: true

# BEGIN Common phases

before_script:
  - cd whork
  - mvn -version
script: 
  - mvn compile
  - mvn test

# END Common phases
