os: linux
dist: focal
language: java
jdk: oraclejdk15
  
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      after_success:
        - cd ..
      before_deploy:
        - ./internal-package.sh config-osx
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: whork-desktop-$TRAVIS_TAG-osx.jar
        on:
          tags: true
    - os: linux
      dist: focal
      addons:
        sonarcloud:
          organization: "stefanobelli"
          token:
            secure: puMDYX7/j5kBkd1hi6sfCFRXPfueBH4sRWaRoh9ypPliozVyUEGz3y8tNIbCZ+xytXR3QzIv93gpnlsyEFfdEXmhkVT4WE1Ig3A6c8Pih3zm5z+rKSuxxnZaU+K+7lS/CxcVxzqEn2TU0+q8wXyCRMgjETUrr3sW3Dsxd8m2oLCI6gKzIjyB6nSy04frDtcv7gCCXt09qEK8sTKt+dlvZibdx0JiH3SQCErutNdohx29NFYrP0J/58lCkXzEtDy7NipJzT8Jh4HimA9He4MLYbdead2MMsNmAuJmpVuGxN1IFNjNsBihnHv3N3zS7COWZ44LpV2nCxBIDxvE/Us6TjSFH6+03ICLLrHOsi+BOuL8L9fnGZxl+OL5xoizwNLwmnvzyOZ3/zXmF87N3Ve0NRa1+G5cgYNW+LOvjK8xRdl2CRwXn5GedLyNp9iZLYnm/HV3txY0AV1zeWLw6D5a6Z5QnXMlHX9ZumNElaCue7mIQgz2ZaRpz8EjTEWnSvKZT7YHEQUyWFcTm2tjlRQl9lu1rSqRvtQeFTGMenWfr+YFAkGBmUDKGhSYgdepjpckwuu6t7mU1bM9Il/cRjrzck+HvftuLpQ3cQiAO5si7WE7GS45fB9xbT+zC6MfQOV0Qak5ZlsV5OB6dDVXgubc/mVyMozQgbKJUy5gZgVgX0Q=
      after_success:
        - cd ..
        - sonar-scanner
      before_deploy:
        - ./internal-package.sh config-linux
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: 
          - whork-webapp-$TRAVIS_TAG-any.jar
          - whork-desktop-$TRAVIS_TAG-linux.jar
        on:
          tags: true
      

# BEGIN Common phases

before_script:
  - cd whork
  - mvn -version
script: 
  - mvn compile
  - mvn test

# END Common phases
