os: linux
dist: focal
language: java
jdk: oraclejdk15
  
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      after_success:
        - cd ..
      before_deploy:
        - ./internal-package.sh config-osx
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: whork-desktop-$TRAVIS_TAG-osx.jar
        on:
          tags: true
    - os: linux
      dist: focal
      addons:
        sonarcloud:
          organization: "stefanobelli"
          token:
            secure: "bVCiqQCUILLFdhSQVyEhusZiyUsiizaUuni/2aE2QrTnHtlg1jzd1PE6GcgMAQxSGqbs09I7cJHvvyqMuM+HmJLMN9TnMlLg0IeshsegB3TnWENlkvAHm+8HZpbpgqV25uibeamL1pp2GVdtGSbqOgRbs+LFpLHmtkvisDwTS6QwJVnLxLMil4hDcAES3NLvo+QA5q6RSkm0/2krgnCM+HEe7gxYlgd0MRqveS/WXS4OBDXGQz0bG4tnEEtmSg+icqzzM9IMrBU9MFjQkq579PIaddQi/PwIt0A+hWL7SvDVNnJDU13UIgcvbmTA/EgUwqRxkZlN29fsSWtCGApmV39To93aw1xzlnt4M9c+BYYlu68tJ759xOlRd9qE3uAC5qmVwP7OEkYjrB9tolgfI+s35nfWO47WG9beGg1s6k8iRDiWNdyRluxIOHv3ENVSWhvk6Tjha9fc9MmWhLzWn31BTQf83Sm6YC1mZ2tRWI5u7XekvArZmeOOts4guu3K5UwxJFTaKyX2ku/w0iZopgAjCr3QxPYmn9z2EslDWjxwr6bmOjcYXSoOGrPU/fXq1n1Nn+cgSd+WRsFAf+J8AKz+xVZWMqKMYs4Ls38xuihnth/ZczhahZ4yAU9HlaHClFBBpov1jO1yc8t+AGZuYOSxh3Kn/pf0S4lbDknk2PY="
      after_success:
        - cd ..
        - sonar-scanner
      before_deploy:
        - ./internal-package.sh config-linux
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        skip_cleanup: true
        file: 
          - whork-webapp-$TRAVIS_TAG-any.jar
          - whork-desktop-$TRAVIS_TAG-linux.jar
        on:
          tags: true
      

# BEGIN Common phases

before_script:
  - cd whork
  - mvn -version
script: 
  - mvn compile
  - mvn test

# END Common phases
